### ISSUE TITLE
BQ漢化用於伺服端

### ISSUE THREAD

**Issue by miaki3457** [yesterday17/GTNH-GuideBook-i18n#1]
請問一下用於伺服是不是無法使用資源包的方式了?

**Comment by Yesterday17** [comment]
伺服器的話應該是不需要安裝資源包的吧，只要客戶端安裝好就行了。
因為原來儲存GuideBook的文件寫入的是硬編碼的英語，而現在修改後就變成了語言條目，在客戶端與服務端交互的時候傳遞的信息就是語言條目信息。資源包只是相當於將語言條目補全罷了。

還有，現在漢化缺人（其實是根本沒有人），來幫忙嗎（2333

**Comment by miaki3457** [comment]
目前翻了100條左右 緩慢推進中

**Comment by Yesterday17** [comment]
@miaki3457 重大勘误说明，详见：#2
