### ISSUE TITLE
Restart after 2018.6.8

### ISSUE THREAD

**Issue by Yesterday17** [yesterday17/GTNH-GuideBook-i18n#10]
明年高考之后估计才能有时间处理这些吧……

Maybe I can only handle it after my university entrance examination on 2018.6.7-6.8, so i can't merge pull requests with confilcts(i don't have the access to my computer).
If possible, you can organize a new fork of this repository and leave an issue here. It can be the base of the localization.

**Comment by b860228b** [comment]
有打算把作者更改的thaumcraft书里的文字提取出来吗?

**Comment by Yesterday17** [comment]
@b860228b 暂时不在计划之内。。还有优先级更高的坑要填（逃
