### ISSUE TITLE
[勘误]你使用的汉化版本可能不适应当前游戏版本

### ISSUE THREAD

**Issue by Yesterday17** [yesterday17/GTNH-GuideBook-i18n#2]
这是我的问题，在当时制作的过程中忽视了。
如果你在汉化的过程中使用的方法是scripts目录下中README.md中的方法，并且没有任何修改的话，那么对于所有版本的GTNH来说，其得到的都是1.4.1.1版本的汉化文件。

现在这个问题已经修复，对应不同的版本已经可以使用不同的json。
注：如果使用旧版本的DefaultQuests.json替换的话，则游戏内容会发生改变，即版本更新带来的任务书更新将不再生效（就相当于用旧版本的任务替换了新版本的一样，游戏过程本身可能没什么感觉，但有些科技线的修复就没办法了）。

对应的1.5.0.7本地化文件地址：
[https://gist.github.com/yesterday17/35645a61db1648ff1a82ba5ac9e9a3d4](https://gist.github.com/yesterday17/35645a61db1648ff1a82ba5ac9e9a3d4)

在这里还是要说一声抱歉，因为我的问题，给各位汉化人员带来了时间上的麻烦（需要通过比对汉化文本来确认修改）。汉化文本升级兼容的工作也在进行中，但由于本人目前处于高三，因此进度几乎停滞……

注2：下一个版本的汉化文件获取以及更新可能抛弃使用浏览器端的方式，改用nodejs。而汉化文件的获取也不一定需要作者本人进行，我可能会使用CI进行编译发布。

**Comment by miaki3457** [comment]
我有修改js內的url到我上傳的位置 感謝
