### ISSUE TITLE
US Localizer

### ISSUE THREAD

**Issue by Dream-Master** [yesterday17/GTNH-GuideBook-i18n#4]
If you can do a us version for newest GTNH i will use it maybe too. Thanks

**Comment by Yesterday17** [comment]
Version 1.5.0.7? See [Here](https://gist.github.com/yesterday17/35645a61db1648ff1a82ba5ac9e9a3d4).
I uploaded it on gist and I'll soon commit it to the repository.

View Raw:
[en_US.lang](https://gist.githubusercontent.com/yesterday17/35645a61db1648ff1a82ba5ac9e9a3d4/raw/f51e7e9657da7bb2261c8ff3ce28fab3dca8e181/en_US.lang)
[DefaultQuests.json](https://gist.githubusercontent.com/yesterday17/35645a61db1648ff1a82ba5ac9e9a3d4/raw/f51e7e9657da7bb2261c8ff3ce28fab3dca8e181/DefaultQuests.json)

**Comment by Dream-Master** [comment]
If this works maybe i switch to this multi Language Tool from you. Sonner or later a GTNH 2.0 will be published.
