### ISSUE TITLE
请问这个项目还需要人手吗？

### ISSUE THREAD

**Issue by Takafate** [yesterday17/GTNH-GuideBook-i18n#5]
我大概一个月前看到这个项目的。当时我看到它只翻译到大概quest50，而且已经一个月没更新了，以为已经坑掉了，就把文件下下来自己翻译了。现在粗翻到quest500，还没校对。刚才看到这个项目又开始更新了，请问我翻译的部分还有用吗？现在有多少人在翻译？我可以把quest51~500校对过后推送过来吗？
我是Github新人，出来炸道，如有冒犯，请多多包涵。

**Comment by miaki3457** [comment]
我這邊有600~700左右的進度

**Comment by Takafate** [comment]
@miaki3457 我注意到了，所以想了解一下有没有其它人同时在做，以免重复造车轮。

**Comment by Yesterday17** [comment]
都是dalao……
你们加油，我这边争取把升级的程序赶出来，这样之后升级能保留很大一部分汉化，否则像现在如果升级的话就只能重新校对……
下学期高三，但如果有pr我会及时merge的（

**Comment by TechnicianFreak** [comment]
因为我玩TC比较多，我想请问能否将TC相关任务及名称校对交给我？看原本翻译TC的专有名词有点问题。

**Comment by Yesterday17** [comment]
@MoXiaoFreak 可以啊 你们可以协调一下 我就负责好好学习吧😂😂😂
@Takafate @miaki3457

**Comment by doctormdkzrp** [comment]
大佬们进度快的能不能先传上来啊？我这边玩边改，机翻加心得的翻译能行不行？

**Comment by TechnicianFreak** [comment]
@doctormdkzrp  吧里有人说已经做了一半了？
